cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'the_silver_searcher'
brew 'coreutils'
brew 'gnutls'
brew 'imagemagick'
brew 'openssl'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'wget'
brew 'thefuck'
brew 'zsh'
brew 'zsh-syntax-highlighting'
brew 'zsh-completions'
brew 'zsh-history-substring-search'

cask 'atom'
cask 'google-chrome'
cask 'transmission'
cask 'slack'

